### ISSUE TITLE
Question about chaos loris

### ISSUE THREAD

**Issue by allomov** [orange-cloudfoundry/chaos-loris-configurer#1]
Hey, @o-orand 

By the design chaos loris app is used behind some service broker that registered all applications from CF in chaos loris app (see https://github.com/strepsirrhini-army/chaos-loris/issues/8 for details). Do you know something about such service broker? Do you run chaos-loris-configurer in production?

Thank you,
Alex L.

**Comment by o-orand** [comment]
Hi Alex,
Sorry, I haven't got any details about a service broker managing Chaos Loris. But it sounds a nice alternative to this project.
Chaos loris configurer is a prototype at the moment, and  it is on hold.

Olivier

**Comment by allomov** [comment]
Since I didn't have a response from @nebhale about the service broker for Chaos Loris (https://github.com/strepsirrhini-army/chaos-loris/issues/8), I've created it by myself. You can check it here https://github.com/Altoros/cf-chaos-loris-broker.

**Comment by o-orand** [comment]
@allomov ,
Thanks for the info.
